import type { Vendor } from '@/lib/types';

const now = new Date().toISOString();

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'mock-1',
    name: "Mama Njoh's Achu Spot",
    quarter: 'Makepe',
    specialty: 'Achu Special — Yellow & Black Soup',
    description: 'Authentic Bamenda-style Achu with fresh pounded cocoyam, served with yellow or black soup. A Douala favorite for over 10 years.',
    price_xaf: 2500,
    rating: 4.9,
    reviews: 127,
    image_url: 'https://images.pexels.com/photos/12924182/pexels-photo-12924182.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 30,
    available: true,
    dish_type: 'achu',
    created_at: now,
  },
  {
    id: 'mock-2',
    name: 'Bamenda Kitchen Kati-Kati',
    quarter: 'Bonapriso',
    specialty: 'Fufu Corn & Kati-Kati Chicken',
    description: 'Tender Kati-Kati chicken with smooth fufu corn. Grilled to perfection with Cameroonian spices. Extra fufu available on request.',
    price_xaf: 2500,
    rating: 4.8,
    reviews: 94,
    image_url: 'https://images.pexels.com/photos/14716239/pexels-photo-14716239.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 25,
    available: true,
    dish_type: 'kati_kati',
    created_at: now,
  },
  {
    id: 'mock-3',
    name: 'Auntie Grace Yellow Soup',
    quarter: 'Akwa',
    specialty: 'Achu Yellow Soup & Black Soup Specialists',
    description: 'The best yellow soup in Akwa! Auntie Grace serves both yellow and black soup with perfectly pounded Achu. Mix available too.',
    price_xaf: 2500,
    rating: 4.9,
    reviews: 156,
    image_url: 'https://images.pexels.com/photos/36874369/pexels-photo-36874369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 35,
    available: true,
    dish_type: 'achu',
    created_at: now,
  },
  {
    id: 'mock-4',
    name: 'Douala Achu Express',
    quarter: 'Kotto',
    specialty: 'Achu Express — Yellow, Black & Mix Soup',
    description: 'Fast Achu delivery across Kotto and Bonanjo. Choose your soup, add tripe or canda, and we will have it hot and ready.',
    price_xaf: 2500,
    rating: 4.7,
    reviews: 82,
    image_url: 'https://images.pexels.com/photos/18015967/pexels-photo-18015967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 28,
    available: true,
    dish_type: 'achu',
    created_at: now,
  },
  {
    id: 'mock-5',
    name: 'Njangi Catering Cooks',
    quarter: 'Bonanjo',
    specialty: 'Bulk Achu & Kati-Kati for Events',
    description: 'Specialists in large-scale Achu and Kati-Kati for weddings, Njangi meetings, and family events. Full menu available — both dishes.',
    price_xaf: 2500,
    rating: 4.8,
    reviews: 63,
    image_url: 'https://images.pexels.com/photos/34772937/pexels-photo-34772937.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 40,
    available: true,
    dish_type: 'full_menu',
    created_at: now,
  },
  {
    id: 'mock-6',
    name: 'Kati-Kati Corner',
    quarter: 'Ndogbong',
    specialty: 'Kati-Kati Chicken & Fufu Corn',
    description: 'The Kati-Kati corner of Ndogbong! Juicy grilled chicken with your choice of standard or extra fufu. Add njama njama for the full experience.',
    price_xaf: 2500,
    rating: 4.6,
    reviews: 51,
    image_url: 'https://images.pexels.com/photos/30268596/pexels-photo-30268596.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 25,
    available: true,
    dish_type: 'kati_kati',
    created_at: now,
  },
  {
    id: 'mock-7',
    name: 'Grassfield Delicacy Hub',
    quarter: 'Ange Raphaël',
    specialty: 'Achu, Yellow & Black Soup, Kati-Kati — Full Menu',
    description: 'A full Grassfield menu in Ange Raphaël! From Achu with your choice of soup to Kati-Kati chicken with fufu. Something for everyone.',
    price_xaf: 2500,
    rating: 4.7,
    reviews: 38,
    image_url: 'https://images.pexels.com/photos/34772940/pexels-photo-34772940.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prep_minutes: 35,
    available: true,
    dish_type: 'full_menu',
    created_at: now,
  },
];
